# -----------------------
# SITE SETTINGS
# -----------------------
title: "Arzu Burcu Güven"
description: "PhD student at IT University of Copenhagen"
url: "https://arzuburcuguven.github.io"
baseurl: ""
repository: "arzuburcuguven/arzuburcuguven.github.io"

# -----------------------
# THEME
# -----------------------
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# -----------------------
# SITE AUTHOR
# -----------------------
author:
  name: "Arzu Burcu Güven"
  avatar: "/assets/images/arzu.jpg" # optional
  bio: "PhD Student in Data Science"
  location: "Copenhagen, Denmark"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:argy@itu.dk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/arzuburcuguven"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/arzu-burcu-güven-4081338b/"
    - label: "Bluesky"
      icon: "fas fa-fw fa-cloud"
      url: "https://bsky.app/profile/arzuburcuguven.bsky.social"

# -----------------------
# FOOTER
# -----------------------


# -----------------------
# READING FILES
# -----------------------
include:
  - _pages
  - .htaccess

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# -----------------------
# PLUGINS
# -----------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# -----------------------
# ARCHIVES
# -----------------------
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# -----------------------
# DEFAULTS
# -----------------------
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# -----------------------
# COLLECTIONS
# -----------------------
collections:
  publications:
    output: true
    permalink: /:collection/:path
  posts:
    output: true
    permalink: /:collection/:path
# -----------------------
# PAGINATION
# -----------------------
paginate: 5
paginate_path: /page:num/

# -----------------------
# MARKDOWN
# -----------------------
markdown: kramdown
